apiVersion: v1
kind: Service
metadata:
  name: wazuh  # Don't change, unless you update the Wazuh dashboard app config
  namespace: wazuh
  labels:
    app: wazuh-manager
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
